<?php

namespace app\models;

use Yii;
use yii\imagine\Image;

/**
 * This is the model class for table "gallery".
 *
 * @property integer $id
 * @property integer $type
 * @property string $title
 * @property string $img
 * @property string $options
 */
class Gallery extends \yii\db\ActiveRecord
{

    public $file;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'gallery';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type', 'galleries_id'], 'integer'],
            [['title', 'img', 'options'], 'string', 'max' => 255],
            [['file'], 'file', 'skipOnEmpty' => false, 'extensions' => 'png, jpg, jpeg, gif', 'on'=>'create'],
        ];
    }
	public function afterFind() {
		parent::afterFind();
		if(!empty($this->options)) {

			$this->options = json_decode($this->options, true);

		}



	}

	public function beforeValidate() {

    	if(parent::beforeValidate()) {

		    if(isset($this->options) and is_array($this->options)) {
				$this->options = json_encode($this->options);
		    }

    		return true;
	    } else {
		    return false;
	    }
    	//return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

	/**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'type' => 'Type',
            'title' => 'Title',
            'img' => 'Img',
        ];
    }


    public function upload($gallery_url, $gallery_controller, $gallery_type = 1)
    {
        if ($this->validate()) {

            if(!empty($this->file)) {

            	//var_dump($this); die();

	            //$path_to_frontend = Yii::getAlias('@webroot/uploads/');
	            $path_to_frontend = Yii::getAlias('@webroot/uploads/' . $gallery_controller . '/' . $gallery_url . '/');
                //$path_to_frontend = '../..' . \Yii::$app->urlManagerFrontend->createUrl('/') . 'uploads/gallerys/';

	            $filename_original =  trim(str_replace(' ', '', $this->file->baseName));


	            if(preg_match('/^[a-z-A-Z0-9-_]*$/', $filename_original))
	            {
		            $filename =  $filename_original;
		            $cnt = 1;
		            while(file_exists($path_to_frontend . $filename . '.' . $this->file->extension)) {

			            $filename = $filename_original . '_' . $cnt;
			            $cnt++;
		            }
	            }
	            else
	            {
		            $filename =  date('ymdHis');
	            }



				$filename = $filename .  '.' . $this->file->extension;


                //var_dump($this->file);

                $this->file->saveAs($path_to_frontend . $filename);


                if(isset($this->img) and !empty($this->img)) {

                    $image = $path_to_frontend . $this->img;
                    $image_small = $path_to_frontend . 'small_' . $this->img;

                    if(file_exists($image)) unlink($image);
                    if(file_exists($image_small)) unlink($image_small);

                }

                $this->img = $filename;

                $img = Image::getImagine()->open($path_to_frontend . $filename);

                $size = $img->getSize();
                $ratio = $size->getWidth()/$size->getHeight();

                $width = 170;
                $height = round($width/$ratio);

                if($size->getWidth() > 800) {
                    $width_original = 800;
                    $height_original = round($width_original/$ratio);

                    Image::thumbnail($path_to_frontend . $filename, $width_original, $height_original)
                         ->save($path_to_frontend  . $filename);
                } else {
                    Image::thumbnail($path_to_frontend . $filename, $size->getWidth(), $size->getHeight())
                         ->save($path_to_frontend  . $filename);
                }


                Image::thumbnail($path_to_frontend . $filename, $width, $height)
                     ->save($path_to_frontend .  'small_' . $filename);

                if($gallery_type == 2) {
                	// tiny size for color galleries
	                Image::thumbnail($path_to_frontend . $filename, 20, 20)
	                     ->save($path_to_frontend .  'tiny_' . $filename);
                }
            }
            return $path_to_frontend . $filename;
        } else {

            return false;
        }
    }


	public function getGalleries() {
		return $this->hasOne( Galleries::className(), [ 'id' => 'galleries_id' ] );
	}

}
